(() => {
    const translateConfig = function (pipTranslateProvider) {
        // Set translation strings for the module
        pipTranslateProvider.translations('en', {
            'SCHEDULE': 'Shedule',
            'SCHEDULE_EMPTY': 'The schedule is empty',
            'UPDATE_OBJECT': 'Add or change objects',
            'ADD_OBJECT': 'Add objects',
            "SCHEDULE_DELETE_OBJECT": 'Remove from schedule',
            'PLANED_OBJECTS': 'Absent',
            "SCHEDULE_ADD_EUEPMENT": 'Assign equipment or asset',
            'ACTUAL_OBJECTS': 'Present',
            'SCHEDULE_WEEK': 'Week of ',
            'APPOINT': 'Assign',
            'AUTO': 'Automatic',
            'FREE': 'Unassigned',
            'ASSINE': 'Assigned',
            'Full day': 'Entire day',
            'SCHEDULE_WORK': 'Works on ',
            'SCHEDULE_TYPE_EMPTY': 'There are no unassigned objects',
            'SCHEDULE_TYPE_DONE': 'There are no assigned objects',
            "SCHEDULE_DELETE_EUEPMENT": 'Remove assignment',
            'DIALOG_CONFIRM_CANCEL': 'Cancel',
            'UNASSIGNED': 'unassigned',
            'ASSIGNED': 'Assigned',

            'LOADING_ROSTERS': 'Loading rosters',
            'SHEDULE_DETAILS_DEFAULT': 'Shedule of the day',
            'ROSTERS_ASSIGNED_NOT_FOUND': 'No assignments for objects',

            SCHEDULE_EMPTY_PEOPLE: 'No assigned peoples',
            SCHEDULE_EMPTY_EQUIPMENT: 'No assigned equipments',
            SCHEDULE_EMPTY_ASSET: 'No assigned assets',
            SCHEDULE_ADD_OBJECT_PEOPLE: 'Add people',
            SCHEDULE_ADD_OBJECT_EQUIPMENT: 'Add equipments',
            SCHEDULE_ADD_OBJECT_ASSET: 'Add assets',
            SCHEDULE_HOUR: 'hours',
            OBJECT_CONFIRMATION_TITLE: 'Would you like to remove from the schedule',
            ROSTER_COPY_SUCCESS: 'Schedule for the next week was successfully copied.',
            ROSTER_COPY_ERROR: 'Errors occurred while copying the schedule.',
            ROSTER_SAVE_ERROR: 'Errors occurred while saving the schedule.',
            ROSTER_NOT_EMPTY: 'Schedule for the next week is not empty. Copying is not possible.',
            CURRENT_ROSTER_EMPTY: 'The schedule for the current week is empty.',
            SCHEDULE_COPY: 'Copy current schedule for next week',
            SCHEDULE_CLEAR: 'Clear schedule',
            ROSTER_CLEAR_CONFIRMATION_TITLE: 'Do you want to clear the schedule for the current week?',
            ROSTER_DELETE_ERROR: 'Errors occurred while deleting the schedule.',
            ROSTER_DELETE_SUCCESS: 'Schedule for this week has been successfully deleted.',
            SCHEDULE_CLEAR_BUTTON: 'Clear',
            'SHIFT_START': 'Start time',
            'SHIFT_END': 'End time',
            '24_HOURS': '24 hours',
            DETAILS: 'Details'
        });

        pipTranslateProvider.translations('ru', {
            'SCHEDULE': 'Расписание',
            'SCHEDULE_EMPTY': 'Расписание пустое',
            'UPDATE_OBJECT': 'Добавить или изменить объекты',
            'ADD_OBJECT': 'Добавить объекты',
            "SCHEDULE_DELETE_OBJECT": 'Убрать из расписания',
            'PLANED_OBJECTS': 'Отсутствуют',
            "SCHEDULE_ADD_EUEPMENT": 'Назначить машину или механизм',
            'ACTUAL_OBJECTS': 'Присутствуют',
            'SCHEDULE_WEEK': 'Неделя от ',
            'APPOINT': 'Назначить',
            'AUTO': 'Автомат',
            'FREE': 'Свободные',
            'Full day': 'Полный день',
            'ASSINE': 'Назначенные',
            'SCHEDULE_WORK': 'Работает на ',
            'SCHEDULE_TYPE_EMPTY': 'Свободных объектов нет',
            'SCHEDULE_TYPE_DONE': 'Назначенных объектов нет',
            "SCHEDULE_DELETE_EUEPMENT": 'Убрать назначение',
            'DIALOG_CONFIRM_CANCEL': 'Отменить',
            'UNASSIGNED': 'Свободные',
            'ASSIGNED': 'Связанные',
            'LOADING_ROSTERS': 'Загрузка расписания',
            'SHEDULE_DETAILS_DEFAULT': 'Расписание на день',
            'ROSTERS_ASSIGNED_NOT_FOUND': 'Назначения для объектов отсутствуют',

            SCHEDULE_EMPTY_PEOPLE: 'Нет назначеных людей',
            SCHEDULE_EMPTY_EQUIPMENT: 'Нет назначенных машин',
            SCHEDULE_EMPTY_ASSET: 'Нет назначенного оборудования',
            SCHEDULE_ADD_OBJECT_PEOPLE: 'Добавить людей',
            SCHEDULE_ADD_OBJECT_EQUIPMENT: 'Добавить машины',
            SCHEDULE_ADD_OBJECT_ASSET: 'Добавить оборудование',
            SCHEDULE_HOUR: 'часа',
            OBJECT_CONFIRMATION_TITLE: 'Удалить из расписания',

            ROSTER_COPY_SUCCESS: 'Расписание успешно скопировано.',
            ROSTER_COPY_ERROR: 'При копировании расписания возникли ошибки.',
            ROSTER_SAVE_ERROR: 'При сохранении расписания возникли ошибки.',
            ROSTER_NOT_EMPTY: 'Расписание на следующую неделю не пустое. Копирование невозможно.',
            CURRENT_ROSTER_EMPTY: 'Расписание на текущую неделю пустое.',
            SCHEDULE_COPY: 'Копировать текущее расписание на следующую неделю',
            SCHEDULE_CLEAR: 'Очистить расписание',
            ROSTER_CLEAR_CONFIRMATION_TITLE: 'Очистить расписание на текущую неделю?',
            ROSTER_DELETE_ERROR: 'При удалении расписания возникли ошибки.',
            ROSTER_DELETE_SUCCESS: 'Расписание на текущую неделю успешно удалено.',
            SCHEDULE_CLEAR_BUTTON: 'Очистить',
            'SHIFT_START': 'Время начала',
            'SHIFT_END': 'Время конца',
            '24_HOURS': '24 часа',
            DETAILS: 'Подробности'
        });
    }

    angular
        .module('iqsSchedule')
        .config(translateConfig);
})();